#! /bin/sh

# kill programs
killall -q dunst
killall -q picom
killall -q sxhkd
killall -q polybar

while pfrep -u $UID -x dunst >/dev/null; do sleep 1; done
while pfrep -u $UID -x picom >/dev/null; do sleep 1; done
while pfrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
while pfrep -u $UID -x fehbg >/dev/null; do sleep 1; done
while pfrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Virtual Machines Autoresize
xrandr --newmode "1920x1080"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
xrandr --addmode Virtual1 1920x1080
xrandr --output Virtual1 --mode 1920x1080

# autostart apps
dunst & 
picom & 
sxhkd &
~/.config/polybar/launch.sh
~/.fehbg

# colors
# FOCUSED_BORDER_COLOR="#5b1d4a"
FOCUSED_BORDER_COLOR="#EA142E"
NORMAL_BORDER_COLOR="#5b5558"
ACTIVE_BORDER_COLOR="#262734"
PRESEL_FEEDBACK_COLOR="#D6A36A"

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width          2
bspc config window_gap            10
Bspc config normal_border_color   "$NORMAL_BORDER_COLOR"
bspc config active_border_color   "$ACTIVE_BORDER_COLOR"
bspc config focused_border_color  "$FOCUSED_BORDER_COLOR"
bspc config presel_feedback_color "$PRESEL_FEEDBACK_COLOR"

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

feh --bg-fill ~/Pictures/Wallpapers/wallpaper_black.png
